###
GET http://localhost:8000/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGF2aWUiLCJyb2xlIjoiYWRtaW4iLCJleHBpcmUiOjE3MTgyNzU4Mjd9.3-yhyWk7OQ1RBuVktqja2XQ8F2j9njVXIJPqVHzOnXI

###

GET http://localhost:8000/city/2
###
# get by id
###
GET  http://localhost:8000/state
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYW50b2hnIiwicm9sZSI6InVzZXIiLCJleHBpcmUiOjE3MTgxOTk0MjN9.m4hEb1H_ipQA1FZBUFj0V91c-NSoiIyvvKEX2vU9M9U
###
GET http://localhost:8000/address
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGF2aWUiLCJyb2xlIjoiYWRtaW4iLCJleHBpcmUiOjE3MTgyMDEyMDl9.0u_zbPZLD59QesfJrD60PbjfO8v7ZoGs2uTNUGXZmUY
###
PUT http://localhost:8000/state/2
 Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZGF2aWUiLCJyb2xlIjoiYWRtaW4iLCJleHBpcmUiOjE3MTgyMDA1MTN9.T7NisJziXqgcYCW3KQcVYvbLNVTY8tp3LBWEs5BEA_w
Content-Type: application/json

{   
      
    "id": 3,
    "name": "kiambu"
  
}

# create something new
###
POST   http://localhost:8000/auth/register
Content-Type: application/json

{
   
    "username": "pinchez",
    "user_id": 8,
     "role": "Driver",

    "password": "pass"
  }

# delete something
###

DELETE http://localhost:8000/city/2
Content-Type: application/json

 {
    "id": 1,
    "name": "antony",
    "contact_phone": "+2547993658",
    "phone_verified": true,
    "email": "antony@gmail.com",
    "email_verified": true,
    "confirmation_code": "2345g",
    "password": "5hg@z3"
  }

#admin
###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "davie",
    "password": "pass"
}

#user
###

POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "antohg",
    "password": "pass"
}

###restaurant owner
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "turoo",
    "password": "pass"
}


###driver
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "pinchez",
    "password": "pass"
}

###
GET http://localhost:8000/user/5/comments